using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace BarracksInventory.Models
{
    [Table("Inspection")]
    public class Inspection
    {
        public int      InspectionId    { get; set; }     // PK, not null, Autogenerated
        [ForeignKey("Unit")]
        public int      UnitId          { get; set; }     // FK, (Unit) not null
        [ForeignKey("Account")]
        public string   SSN             { get; set; }     // FK, (Account) not null
        public DateTime Date            { get; set; }     // not null, date
        public string   Location        { get; set; }     // not null
        public string   Status          { get; }          // restrict status
    }
}