using System.ComponentModel.DataAnnotations.Schema;

namespace BarracksInventory.Models
{

    [Table("InventoryItem")]
    public class InventoryItem
    {
        public int      itemId      { get; set; }     // PK, not null, Autogenerated
        public int      userId      { get; set; }     // FK, (Account) not null
        public string   itemName    { get; set; }     // not null nvarcar 40
        public int      qty         { get; set; }     // not null
        [Column(TypeName = "decimal(8, 2)")]
        public decimal itemPrice { get; set; }     // not null
    }
}