using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BarracksInventory.Models
{

    [Table("Item")]
    public class Item
    {
        public int      ItemId      { get; set; }     // PK, not null, Autogenerated

        [ForeignKey("Account")]
        public string   SSN         { get; set; }     // FK, (Account) not null

        [Required(ErrorMessage = "Must have an item name.")]
        public string   Name        { get; set; }     // not null nvarcar 40

        [Required(ErrorMessage = "Must have an item quantity.")]
        public int      Qty         { get; set; }     // not null

        [Column(TypeName = "decimal(8, 2)")]
        public decimal  Price       { get; set; }     // not null
    }
}