using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System;

namespace BarracksInventory.Models
{
    [Table("Inspection")]
    public class Inspection
    {
        public int      InspectionId    { get; set; }     // PK, not null, Autogenerated

        [ForeignKey("Unit")]
        public int      UnitId          { get; set; }     // FK, (Unit) not null

        [ForeignKey("Account")]
        public string   SSN             { get; set; }     // FK, (Account) not null

        [Required(ErrorMessage = "Must have a inspector name.")]
        public string   InspectorName   { get; set; }

        [Required(ErrorMessage = "Must have a date & time inspection completed.")]
        public DateTime Date            { get; set; }     // not null, date

        [Required(ErrorMessage = "Must have a inspection location.")]
        public string   Location        { get; set; }     // not null

        [Required(ErrorMessage = "Must have a inspection status.")]
        public string   Status          { get; }          // restrict status
    }
}